---
MONOSPACE_FONT_POINT: 14

# list of packages to install for each OS
OS_PACKAGES:
  debian:
  - vim-gtk # gives +clipboard feature
  - rsync
  - i3
  - suckless-tools
  - surf
  - stterm
  - dunst
  - firefox-esr
  - zsh
  - msmtp
  - openconnect
  - network-manager-openconnect
  - network-manager-openconnect-gnome # for the desktop applet
  - x11-xserver-utils # provides xset
  - pulseaudio

GUIX_PACKAGES:
- glibc-locales
- notmuch
- offlineimap
- alot
- notmuch-addrlookup-c
- isync
- vdirsyncer
- bitlbee

#tools_src_dir: tools

