# required variables:
#
# name: e.g. bleh
# vhost: e.g. sbk.sankey.info (passed to www-vhost)
# alias: e.g. /bleh
# location: e.g. /data/www/bleh
# cgi: default false

- name: setup alias conf
  template:
    src: alias.conf
    dest: /etc/nginx/vhosts.d/{{ alias_vhost }}.conf.d/{{ name }}.conf
  register: setup_conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: setup_conf|changed

- name: ensure fcgiwrap is running
  service:
    name: fcgiwrap
    state: started
