---
- name: install various packages from guix
  command: "{{ GUIX_BIN }}/guix package -i python@2.7 python2-virtualenv python2-pip"
# just in case the pip deps need them
- name: install tahoe build dependencies
  command: apt-get --assume-yes build-dep tahoe-lafs
- name: install extra tahoe build dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - libffi-dev
  - libssl-dev
- name: install virtualenv using updated python
  command: "{{ GUIX_BIN }}/virtualenv-2.7 -p {{ GUIX_BIN }}/python2.7 {{ VENV }}"
  args:
    creates: /opt/tahoe.venv
- name: install tahoe-lafs and dependencies into virtualenv
  pip:
    name: "{{ PYPI_PACKAGE }}"
    executable: "{{ GUIX_BIN }}/pip2.7"
    virtualenv: "{{ VENV }}"
    virtualenv_command: "{{ GUIX_BIN }}/virtualenv-2.7"
- name: install tahoe command symlink
  file:
    src: "{{ VENV }}/bin/tahoe"
    dest: /usr/local/bin/tahoe
    state: link
