---
- name: install various packages from guix
  shell: $HOME/.guix-profile/bin/guix package -i python@2.7 virtualenv python2-pip
- name: install various backup packages from debian
  # use shell instead of command in case guix has been updated after installing
  apt:
    name: {{ item }}
    state: latest
  with_items:
  - python-pip
- name: install virtualenv, 
  apt:
    name: virtualenv
    state: latest
- name: install tahoe runtime dependencies
  apt:
    name: tahoe-lafs
    state: latest
- name: install tahoe build dependencies
  apt:
    name: tahoe-lafs
    state: build-dep
- name: fetch tahoe tarball
  get_url:
    url: "{{ TAHOE_URL }}"
    sha256sum: "{{ TAHOE_SHA256 }}"
    dest: /root/
- name: install virtualenv using updated python
  shell: $HOME/.guix-profile/bin/virtualenv -p python2.7 /opt/tahoe.venv
  args:
    creates: /opt/tahoe.venv
- name: install tahoe-lafs and dependencies into virtualenv
  pip:
    name: tahoe-lafs
    executable: /root/.guix-profile/bin/pip2.7
    virtualenv: /opt/tahoe.venv
- name: install systemd service
  # TODO
