---
- name: install various packages from guix
  command: "{{ GUIX_BIN }}/guix package -i python@2.7 virtualenv python2-pip"
# just in case the pip deps need them
- name: install tahoe build dependencies
  apt:
    name: tahoe-lafs
    state: build-dep
- name: install virtualenv using updated python
  command: "{{ GUIX_BIN }}/virtualenv -p {{ GUIX_BIN }}/python2.7 {{ VENV }}"
  args:
    creates: /opt/tahoe.venv
- name: install tahoe-lafs and dependencies into virtualenv
  pip:
    name: "{{ PYPI_PACKAGE }}"
    executable: "{{ GUIX_BIN }}/pip2.7"
    virtualenv: "{{ VENV }}"
- name: install tahoe command symlink
  file:
    src: "{{ VENV }}/bin/tahoe"
    dest: /usr/local/bin/tahoe
    state: link
