- name: install ethercalc
  npm:
    name: ethercalc
    state: latest
    global: true
- name: install ethercalc user
  user:
    name: ethercalc
    system: true
- name: install ethercalc service
  copy:
    src: ethercalc.service
    dest: /etc/systemd/system/ethercalc.service
- name: start ethercalc service
  service:
    name: ethercalc
    state: started
- name: enable ethercalc service
  service:
    name: ethercalc
    enabled: true
- name: setup proxy conf
  template:
    src: proxy.conf
    dest: /etc/nginx/vhosts.d/{{ proxy_vhost }}.conf.d/{{ proxy_name }}.conf
  register: setup_conf
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: setup_conf|changed
