---
#- name: update apt cache
#  sudo: True
#  apt: update_cache=yes
- name: install development related packages
  sudo: True
  apt:
    name: '{{ item }}'
  with_items:
  - git
  - build-essential
  - strace
  - virtualenvwrapper
  - python-virtualenv
  - python-dev
  - python3-dev
  - pyflakes
  - pylint
  - lxc
  - libvirt-bin
  - libvirt-clients
  - ansible
  - rhc
  - jq
  - libjpeg-dev
  - libffi-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - nfs-kernel-server

# TODO: put condition on this to only install for edx
- name: install newer software from backports
  sudo: True
  apt:
    name: '{{ item }}'
    state: latest
    default_release: jessie-backports
  with_items:
  - virtualbox
  - virtualbox-dkms
  - virtualbox-qt
  - virtualbox-guest-dkms
  - virtualbox-guest-utils

# TODO: put condition on this to only install for edx
- name: install newer software from stretch
  sudo: True
  apt:
    name: '{{ item }}'
    state: latest
    default_release: stretch
  with_items:
  - virtualbox-guest-additions-iso

# TODO: put condition on this to only install for edx
# fetch and install vagrant
- name: fetch vagrant
  sudo: True
  get_url:
    url: 'https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb'
    dest: /root
  when: ansible_distribution == 'Debian' and ansible_architecture == "x86_64"
  tags:
  - vagrant
- name: install vagrant
  sudo: True
  apt:
    deb: /root/vagrant_1.8.1_x86_64.deb
  when: ansible_distribution == 'Debian' and ansible_architecture == "x86_64"
  tags:
  - vagrant
