# required variables:
#
# sbk_vhost: e.g. sbk.sankey.info (passed to www-vhost)

# nginx stuff
- name: setup alias conf
  template:
    src: sbk.conf
    dest: "{{ HTTPD_VHOSTS }}/{{ vhost }}.conf.d/sbk.conf"
  register: setup_conf
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: setup_conf|changed
- name: ensure fcgiwrap is running
  service:
    name: fcgiwrap
    state: started
- name: ensure fcgiwrap is enabled
  service:
    name: fcgiwrap
    enabled: true

# deploy the code
- name: ensure code is present
  git:
    repo: https://github.com/somervillebikekitchen/somervillebikekitchen.github.io.git
    dest: /data/www/{{ vhost }}
    depth: 1
