---
- name: ensure the sankey user exists
  user:
    name: sankey
    createhome: yes
    group: sankey
    groups: sudo
- name: ensure my key is in .ssh/authorized_keys
  script: "findsum.sh {{ PUBKEY_SHA512 }} /home/sankey/.ssh/authorized_keys"
  register: authorized_keys
- name: fail if we can't login via pubkey
  fail:
    msg: >
      Could not find an appropriate ssh public key.  Failing ansible to prevent
      lockout.
  when: authorized_keys.rc != 0

# among other things, the following task will DISABLE PASSWORD-ONLY LOGINS
- name: install our sshd_config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
