---
- name: setup vhost conf
  template:
    src: vhost.conf
    dest: /etc/nginx/vhosts.d/{{ www_vhost_fqdn }}.conf
    mode: 0644
    owner: root
    group: root
  
- name: setup vhost dir
  file:
    path: /etc/nginx/vhosts.d/{{ www_vhost_fqdn }}.conf.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: setup docroot dir
  file:
    path: /data/www/{{ www_vhost_fqdn }}
    state: directory
