---
- name: setup vhost conf
  template:
    src: vhost.conf
    dest: "{{ HTTPD_VHOSTS }}/{{ fqdn }}.conf"
    mode: 0644
    owner: root
    group: root
  
- name: setup vhost dir
  file:
    path: "{{ HTTPD_VHOSTS }}/{{ fqdn }}.conf.d"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: setup docroot dir
  file:
    path: "{{ HTTPD_DOCROOTS }}/{{ fqdn }}"
    state: directory
    mode: 0775
    owner: www-data
    group: www-data
