---
############
# packages #
############
#- name: update apt cache
#  become: True
#  apt: update_cache=yes
- name: install common packages
  become: True
  apt: name={{ item }}
  with_items: "{{ OS_PACKAGES.debian }}"

#- name: install software from guix
#  command: "guix package -i {{ GUIX_PACKAGES|join(' ') }}"

- name: setup torproject repo key
  become: True
  apt_key:
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present
    keyserver: "{{ KEYSERVER }}"
- name: setup torproject repo
  become: True
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org jessie main
    state: present
    update_cache: yes

- name: configure ~/bin
  synchronize: src=roles/desktop-laptop/files/bin/ dest=~/bin/

############
# dotfiles #
############
- name: configure xinitrc
  copy: src=xinitrc dest=~/.xinitrc
- name: setup i3 config dir
  file:
    path: ~/.i3
    state: directory
- name: configure i3
  template: src=i3/config dest=~/.i3/config
- name: configure i3status
  copy: src=i3status.conf dest=~/.i3status.conf
- name: configure vim
  copy: src=vimrc dest=~/.vimrc
- name: configure vim plugins
  synchronize:
    src: roles/desktop-laptop/files/vim/
    dest: ~/.vim/
- name: configure zsh
  copy: src=zshrc dest=~/.zshrc
- name: ensure default shell is zsh
  become: True
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
- name: configure surf
  synchronize:
    src: roles/desktop-laptop/files/surf/
    dest: ~/.surf/

##############################
# suspend and screen locking #
##############################

- name: install screen locking service/handler
  become: True
  template:
    src: slock.service
    dest: /etc/systemd/system/slock.service
- name: enable screen locking service/handler
  become: True
  service:
    name: slock
    enabled: true

##################
# suckless tools #
##################
#- name: setup suckless tools dir
#  file: path={{ tools_src_dir }} state=directory
#- include: install_suckless_tool.yml
#  vars:
#    name: dmenu
#    version: b3d9451c2ddfad7c1b10e9a868afed4d92b37e41
#- include: install_suckless_tool.yml
#  vars:
#    name: slock
#    version: 65b8d5278882310eed758e6fbfd6ab9676db883c
#- include: install_suckless_tool.yml
#  vars:
#    name: st
#    version: ff241199edc7631d6599c22414ef6823059a1072
#- include: install_suckless_tool.yml
#  vars:
#    name: surf
#    version: f5e8baad06eafef22df12ab2649139260127d4e4
