
node3:
	ansible-playbook -i inventory.ini $@.yml
node4:
	ansible-playbook -i inventory.ini $@.yml
personal-laptop:
	ansible-playbook -i inventory.ini $@.yml
work-laptop:
	ansible-playbook -i inventory.ini $@.yml

.PHONY: node3 node4
