---
- hosts: localhost
  vars:
    FQDN: node4.sankey.info
    PUBLIC_IPV4:
    - 69.61.93.76
    PUBLIC_IPV6:
    - 2607:1a00:0:19::2:f3
    - 2607:1a00:0:19::2:f1
    - 2607:1a00:0:19::2:f0
    - 2607:1a00:0:19::2:f2
  roles:
  - server-common
  - guix

  - etherpad
  - role: www-reverse-proxy
    name: etherpad
    vhost: sbk.sankey.info
    alias: /calc/
    proxy_host: localhost
    proxy_port: 8000
    proxy_rewrite_port: 8001

  # sbk website
  - role: www
    name: sbk
    vhost: sbk.sankey.info
    alias: /
    location: /data/www/sbk/
    cgi: true


#  # storage server
#  - role: tahoe-storage
#    location: /data/tahoe-storage
#    capacity: 20
#
#    
#  # my homepage
#  - role: tahoe-mnt
#    location: www/troy
#    mountpoint: /data/www/troy
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/troy
#    cgi: true
#
#  # Lyn's homepage
#  - role: tahoe-mnt
#    location: www/lyn
#    mountpoint: /data/www/lyn
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/lyn
#    cgi: true
#
#  # tmp
#  - role: tahoe-mnt
#    location: www/tmp
#    mountpoint: /data/www/tmp
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/tmp
#
#  # rand
#  - role: tahoe-mnt
#    location: www/rand
#    mountpoint: /data/www/rand
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/rand
