---
- hosts: localhost
  vars:
    FQDN: node3.sankey.info
    PUBLIC_IPV4:
    - 98.217.8.51
    PUBLIC_IPV6: []
  roles:
  - role: server-common
    SSH_LAN_PUBKEY_ONLY: true
  - guix

  - role: files
    files_vhost: files.sankey.info

#  # storage server
#  - role: tahoe-storage
#    location: /data/tahoe-storage
#    capacity: 50
#
#  # my homepage
#  - role: tahoe-mnt
#    location: www/troy
#    mountpoint: /data/www/troy
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/troy
#    cgi: true
