---
- hosts: localhost
  vars:

    # hard facts
    FQDN: node3.sankey.info
    NODENAME: node3
    PUBLIC_IPV4:
    - 98.217.8.51
    PUBLIC_IPV6: []

    # derived facts
    ALL_OTHER_NODES: "{{ ALL_NODES|reject('match', NODENAME)|list }}"

  roles:
  - role: server-common
    SSH_LAN_PUBKEY_ONLY: true
  - guix
  - tor

  - role: www-vhost
    fqdn: troy.sankey.info
  - role: www-conf
    name: troy
    vhost: troy.sankey.info

  - role: www-vhost
    fqdn: files.sankey.info
  - role: www-conf
    name: files
    vhost: files.sankey.info

  - role: www-vhost
    fqdn: node3.sankey.info
  - role: alias
    name: movies
    vhost: node3.sankey.info
    alias: /movies/
    location: /data/movies/
  - role: alias
    name: music
    vhost: node3.sankey.info
    alias: /music/
    location: /data/music/

#  # storage server
#  - role: tahoe-storage
#    location: /data/tahoe-storage
#    capacity: 50
#
#  # my homepage
#  - role: tahoe-mnt
#    location: www/troy
#    mountpoint: /data/www/troy
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/troy
#    cgi: true
