---
- hosts: localhost
  vars:
    FQDN: node4.sankey.info
    PUBLIC_IPV4:
    - 69.61.93.76
    PUBLIC_IPV6:
    - 2607:1a00:0:19::2:f3
    - 2607:1a00:0:19::2:f1
    - 2607:1a00:0:19::2:f0
    - 2607:1a00:0:19::2:f2
  roles:
  - server-common
  - guix

  # ethercalc instance
  - role: www-vhost
    fqdn: calc.sankey.info
  - role: ethercalc
    vhost: calc.sankey.info

  # sbk website
  - role: www-vhost
    fqdn: sbk.sankey.info
  - role: sbk
    vhost: sbk.sankey.info

  # sgmc website
  - role: www-vhost
    fqdn: sgmc.sankey.info
  - role: sgmc
    vhost: sgmc.sankey.info

#  # storage server
#  - role: tahoe-storage
#    location: /data/tahoe-storage
#    capacity: 20
#
#    
#  # my homepage
#  - role: tahoe-mnt
#    location: www/troy
#    mountpoint: /data/www/troy
#    user: www-data
#    group: www-data
#    mode: 0444
  - role: www-vhost
    fqdn: troy.sankey.info
  - role: www-conf
    name: troy
    vhost: troy.sankey.info
#
#  # Lyn's homepage
#  - role: tahoe-mnt
#    location: www/lyn
#    mountpoint: /data/www/lyn
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/lyn
#    cgi: true
#
#  # tmp
#  - role: tahoe-mnt
#    location: www/tmp
#    mountpoint: /data/www/tmp
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/tmp
#
#  # rand
#  - role: tahoe-mnt
#    location: www/rand
#    mountpoint: /data/www/rand
#    user: www-data
#    group: www-data
#    mode: 0444
#  - role: www
#    location: /data/www/rand
