# CUSTOM TASKS

# files
- name: ensure client temp directory
  file:
    path: "{{ files_uploads_temp }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  when: "{{ name == 'files' }}"
