# required variables:
#
# name: e.g. sbk
# vhost: e.g. sbk.sankey.info

# nginx stuff
- name: setup alias conf
  template:
    src: "{{ name }}.conf"
    dest: "{{ vhost_dir }}/{{ name }}.conf"
  register: setup_conf
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: setup_conf|changed

# fcgiwrap
- name: ensure fcgiwrap is running
  service:
    name: fcgiwrap
    state: started
  when: "{{ fcgiwrap_enabled }}"
- name: ensure fcgiwrap is enabled
  service:
    name: fcgiwrap
    enabled: true
  when: "{{ fcgiwrap_enabled }}"

# site content
- name: deploy content via git
  git:
    repo: "{{ CONTENT_SOURCE['git'][name] }}"
    dest: "{{ docroot }}"
    depth: 1
  when: "{{ CONTENT_SOURCE['git'].has_key(name) }}"

# custom
- include: custom.yml
